theme: jekyll-theme-minimal
title: GGA
logo: gga-clean.png
description: Galaxy Genome Annotation
show_downloads: false

# Overriding these so it reads in a more sensible manner
github:
    is_project_page: true
    is_user_page: false
    repository_url: https://github.com/galaxy-genome-annotation/
