theme: jekyll-theme-minimal
title: GGA
description: <img src="gga-clean.png" style="max-width:100%" />
show_downloads: false

# Overriding these so it reads in a more sensible manner
github:
    is_project_page: true
    is_user_page: false
    repository_url: https://github.com/galaxy-genome-annotation/
